# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/topics/items.html

from scrapy.item import Item, Field


class GasolineCar(Item):
    url = Field()
    acquisition_date = Field()

    manufacturer = Field()
    name = Field()
    image = Field()

    new_car_price = Field()
    used_car_price = Field()
    ranking = Field()
    rating_value = Field()
    rating_count = Field()

    release_date = Field()
    sale_status = Field()
    sale_division = Field()
    model = Field()
    transmission = Field()
    handle_position = Field()
    drive_system = Field()
    riding_capacity = Field()
    full_length = Field()
    full_height = Field()
    full_width = Field()
    car_weight = Field()
    minimum_turning_radius = Field()
    power = Field()
    kmperliter_with_jc08mode = Field()
    kmperliter_with_1015mode = Field()
    fuel_efficiency_achievement_rate = Field()

    cylinder_capacity = Field()
    fuel_type = Field()
    fuel_tank_capacity = Field()
    supercharger = Field()
    maximum_output = Field()
    maximum_torque = Field()
    antilock_brake_system = Field()
    electronic_stability_control = Field()
    airbag = Field()
    side_airbag = Field()
    curtain_airbag = Field()
    idle_reduction = Field()
    cruise_control = Field()
    car_navigation_system = Field()
    front_wheel_size = Field()
    rear_wheel_size = Field()
    available_colors = Field()
    ecocar_tax_reduction = Field()
    car_acquisition_tax = Field()
    car_weight_tax = Field()
    next_year_car_tax = Field()


class HybridCar(Item):
    url = Field()
    acquisition_date = Field()

    manufacturer = Field()
    name = Field()
    image = Field()

    new_car_price = Field()
    used_car_price = Field()
    ranking = Field()
    rating_value = Field()
    rating_count = Field()

    release_date = Field()
    sale_status = Field()
    sale_division = Field()
    model = Field()
    transmission = Field()
    handle_position = Field()
    drive_system = Field()
    riding_capacity = Field()
    full_length = Field()
    full_height = Field()
    full_width = Field()
    car_weight = Field()
    minimum_turning_radius = Field()
    power = Field()
    kmperliter_with_jc08mode = Field()
    kmperliter_with_1015mode = Field()
    fuel_efficiency_achievement_rate = Field()

    cylinder_capacity = Field()
    fuel_type = Field()
    fuel_tank_capacity = Field()
    supercharger = Field()
    maximum_output = Field()
    maximum_torque = Field()

    motor_maximum_output = Field()
    motor_maximum_torque = Field()

    antilock_brake_system = Field()
    electronic_stability_control = Field()
    airbag = Field()
    side_airbag = Field()
    curtain_airbag = Field()
    idle_reduction = Field()
    cruise_control = Field()
    car_navigation_system = Field()
    front_wheel_size = Field()
    rear_wheel_size = Field()
    available_colors = Field()
    ecocar_tax_reduction = Field()
    car_acquisition_tax = Field()
    car_weight_tax = Field()
    next_year_car_tax = Field()


class ElectricCar(Item):
    url = Field()
    acquisition_date = Field()

    manufacturer = Field()
    name = Field()
    image = Field()

    new_car_price = Field()
    used_car_price = Field()
    ranking = Field()
    rating_value = Field()
    rating_count = Field()

    release_date = Field()
    sale_status = Field()
    sale_division = Field()
    model = Field()
    transmission = Field()
    handle_position = Field()
    drive_system = Field()
    riding_capacity = Field()
    full_length = Field()
    full_height = Field()
    full_width = Field()
    car_weight = Field()
    minimum_turning_radius = Field()
    power = Field()

    battery_capacity = Field()
    running_distance = Field()
    charging_time_100v = Field()
    charging_time_200v = Field()
    charging_time_rapid = Field()

    motor_maximum_output = Field()
    motor_maximum_torque = Field()

    antilock_brake_system = Field()
    electronic_stability_control = Field()
    airbag = Field()
    side_airbag = Field()
    curtain_airbag = Field()
    idle_reduction = Field()
    cruise_control = Field()
    car_navigation_system = Field()

    front_wheel_size = Field()
    rear_wheel_size = Field()
    available_colors = Field()
    ecocar_tax_reduction = Field()
    car_acquisition_tax = Field()
    car_weight_tax = Field()
    next_year_car_tax = Field()
